---
version: '3.4'

x-defaults: &defaults
  image: "itbrowz"
  build:
    dockerfile: ./docker/Dockerfile
    context: .
  environment:
    PYENV_VERSION: "itbrowz"
    LANG: 'en_US.UTF-8'
  entrypoint: /bin/bash
  volumes:
    - ./:/app

services:
  itbrowz:
    <<: *defaults
    entrypoint: python3 -m itbrowz
    # The "@" indicates that all arguments will be passed to the script called by `entrypoint`
    command: "@"

  # run tests & lints
  test:
    <<: *defaults
    command: docker/run_tests.sh --format-code

  test-integration:
    <<: *defaults
    command: docker/run_tests.sh --format-code --integration

  # Create an updated requirements.lock
  lock-requirements:
    <<: *defaults
    command: docker/lock_requirements.sh

volumes:
  home:
  venv:
    driver: local
