#!/usr/bin/env bash

pip3 freeze | xargs pip3 uninstall -y
pip3 install -r requirements.txt
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" > requirements.lock
pip3 freeze --disable-pip-version-check >> requirements.lock
